services:
  - type: web
    name: onnx-ia
    env: node
    buildCommand: npm install --legacy-peer-deps --timeout=180000
    startCommand: npm run web
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
